# Generated by Django 4.1 on 2022-08-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
